namespace: "unistra"
name: "glpi"
version: "1.1.1"
readme: "README.rst"
authors:
- "François Ménabé <francois.menabe@unistra.fr>"
dependencies: {}
license:
- "GPL3"
tags:
- glpi
repository: "https://github.com/unistra/ansible-collection-glpi"
issues: "https://github.com/unistra/ansible-collection-glpi/issues"
